/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *Jdialog qui permet au joueur de choisir un sac
 */
public class ChoixSac extends javax.swing.JDialog {

    /**
     * Creates new form ChoixSac
     */
    private int choix;

    public int getChoix() {
        return choix;
    }
    public ChoixSac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jrbBlanc.setSelected(true);
        choixSac.add(jrbBlanc);
        choixSac.add(jrbBleu);
        choixSac.add(jrbVert);
        choixSac.add(jrbNoir);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choixSac = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        jrbBlanc = new javax.swing.JRadioButton();
        jrbBleu = new javax.swing.JRadioButton();
        jrbVert = new javax.swing.JRadioButton();
        jrbNoir = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(598, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Dans quel sac voulaez vous mettre les Vikings?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        valider.setBackground(new java.awt.Color(0, 0, 0));
        valider.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        valider.setForeground(new java.awt.Color(0, 255, 255));
        valider.setText("Valider");
        valider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        valider.setContentAreaFilled(false);
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        jPanel1.add(valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        Annuler.setBackground(new java.awt.Color(0, 0, 0));
        Annuler.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        Annuler.setForeground(new java.awt.Color(0, 255, 255));
        Annuler.setText("Annuler");
        Annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        Annuler.setContentAreaFilled(false);
        Annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerMouseClicked(evt);
            }
        });
        jPanel1.add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jrbBlanc.setBackground(java.awt.Color.black);
        jrbBlanc.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbBlanc.setForeground(new java.awt.Color(0, 255, 255));
        jrbBlanc.setText("Blanc");
        jPanel1.add(jrbBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jrbBleu.setBackground(java.awt.Color.black);
        jrbBleu.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbBleu.setForeground(new java.awt.Color(0, 255, 255));
        jrbBleu.setText("Bleu");
        jPanel1.add(jrbBleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jrbVert.setBackground(new java.awt.Color(0, 0, 0));
        jrbVert.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbVert.setForeground(new java.awt.Color(0, 255, 255));
        jrbVert.setText("Vert");
        jPanel1.add(jrbVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jrbNoir.setBackground(java.awt.Color.black);
        jrbNoir.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbNoir.setForeground(new java.awt.Color(0, 255, 255));
        jrbNoir.setText("Noir");
        jPanel1.add(jrbNoir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseClicked
        // TODO add your handling code here:
        choix=-1;
        this.dispose();
    }//GEN-LAST:event_AnnulerMouseClicked

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        // TODO add your handling code here:
        if (jrbBlanc.isSelected()) {
            choix=0;
        } else if (jrbBleu.isSelected()) {
            choix=1;
        } else if (jrbVert.isSelected()) {
            choix=2;
        } else if (jrbNoir.isSelected()) {
            choix=3;
        }
        this.dispose();
    }//GEN-LAST:event_validerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoixSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoixSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoixSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoixSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ChoixSac dialog = new ChoixSac(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.ButtonGroup choixSac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbBlanc;
    private javax.swing.JRadioButton jrbBleu;
    private javax.swing.JRadioButton jrbNoir;
    private javax.swing.JRadioButton jrbVert;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
