/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yggdrasil.vue;

/**
 *
 * @author Mathias
 */
public class choixEnnemi extends javax.swing.JDialog {

    /**
     * Creates new form choixEnnemi
     */
    private int choix;

    public choixEnnemi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jrbHel.setSelected(true);
        choixGroupeBouton.add(jrbFenrir);
        choixGroupeBouton.add(jrbHel);
        choixGroupeBouton.add(jrbJormungand);
        choixGroupeBouton.add(jrbLoki);
        choixGroupeBouton.add(jrbNidhogg);
        choixGroupeBouton.add(jrbSurt);
    }

    public int getChoix() {
        return choix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choixGroupeBouton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        jrbHel = new javax.swing.JRadioButton();
        jrbSurt = new javax.swing.JRadioButton();
        jrbJormungand = new javax.swing.JRadioButton();
        jrbLoki = new javax.swing.JRadioButton();
        jrbNidhogg = new javax.swing.JRadioButton();
        jrbFenrir = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Quels dieux voulez vous combattre?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        valider.setBackground(new java.awt.Color(0, 0, 0));
        valider.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        valider.setForeground(new java.awt.Color(0, 255, 255));
        valider.setText("Valider");
        valider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        valider.setContentAreaFilled(false);
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        jPanel1.add(valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        Annuler.setBackground(new java.awt.Color(0, 0, 0));
        Annuler.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        Annuler.setForeground(new java.awt.Color(0, 255, 255));
        Annuler.setText("Annuler");
        Annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        Annuler.setContentAreaFilled(false);
        Annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerMouseClicked(evt);
            }
        });
        jPanel1.add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        jrbHel.setBackground(java.awt.Color.black);
        jrbHel.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbHel.setForeground(new java.awt.Color(0, 255, 255));
        jrbHel.setText("Hel");
        jPanel1.add(jrbHel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jrbSurt.setBackground(java.awt.Color.black);
        jrbSurt.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbSurt.setForeground(new java.awt.Color(0, 255, 255));
        jrbSurt.setText("Surt");
        jrbSurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSurtActionPerformed(evt);
            }
        });
        jPanel1.add(jrbSurt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jrbJormungand.setBackground(new java.awt.Color(0, 0, 0));
        jrbJormungand.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbJormungand.setForeground(new java.awt.Color(0, 255, 255));
        jrbJormungand.setText("Jormungand");
        jPanel1.add(jrbJormungand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jrbLoki.setBackground(java.awt.Color.black);
        jrbLoki.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbLoki.setForeground(new java.awt.Color(0, 255, 255));
        jrbLoki.setText("Loki");
        jPanel1.add(jrbLoki, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jrbNidhogg.setBackground(java.awt.Color.black);
        jrbNidhogg.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbNidhogg.setForeground(new java.awt.Color(0, 255, 255));
        jrbNidhogg.setText("Nidhogg");
        jPanel1.add(jrbNidhogg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jrbFenrir.setBackground(java.awt.Color.black);
        jrbFenrir.setFont(new java.awt.Font("Yggdrasil", 0, 18)); // NOI18N
        jrbFenrir.setForeground(new java.awt.Color(0, 255, 255));
        jrbFenrir.setText("Fenrir");
        jPanel1.add(jrbFenrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        // TODO add your handling code here:
        if (jrbHel.isSelected()) {
            choix = 0;
        } else if (jrbSurt.isSelected()) {
            choix = 1;
        } else if (jrbJormungand.isSelected()) {
            choix = 2;
        } else if (jrbLoki.isSelected()) {
            choix = 3;
        } else if (jrbNidhogg.isSelected()) {
            choix = 4;
        } else if (jrbFenrir.isSelected()) {
            choix = 5;
        }
        this.dispose();
    }//GEN-LAST:event_validerMouseClicked

    private void AnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseClicked
        // TODO add your handling code here:
        choix = -1;
        this.dispose();
    }//GEN-LAST:event_AnnulerMouseClicked

    private void jrbSurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSurtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSurtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choixEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choixEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choixEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choixEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                choixEnnemi dialog = new choixEnnemi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.ButtonGroup choixGroupeBouton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbFenrir;
    private javax.swing.JRadioButton jrbHel;
    private javax.swing.JRadioButton jrbJormungand;
    private javax.swing.JRadioButton jrbLoki;
    private javax.swing.JRadioButton jrbNidhogg;
    private javax.swing.JRadioButton jrbSurt;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
