/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yggdrasil.vue;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Mathias
 */
public class ChoixOrdreCarteEnnemi extends javax.swing.JDialog {

    /**
     * Creates new form ChoixOrdreCarteEnnemi
     */
    private static ArrayList<String> pileCarteEnnemis;
    private int[] ordre;

    public ChoixOrdreCarteEnnemi(java.awt.Frame parent, boolean modal, ArrayList<String> pileCarteEnnemis) {
        super(parent, modal);
        this.ordre = new int[6];
        for (int o : ordre) {
            o = 0;
        }
        this.pileCarteEnnemis = pileCarteEnnemis;
        initComponents();
        premiereCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(0).toString() + "C.png")));
        secondeCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(1).toString() + "C.png")));
        troisiemeCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(2).toString() + "C.png")));
        quatriemeCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(3).toString() + "C.png")));
        cinquiemeCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(4).toString() + "C.png")));
        sixiemeCarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yggdrasil/vue/" + pileCarteEnnemis.get(5).toString() + "C.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sixiemeCarte = new javax.swing.JLabel();
        cinquiemeCarte = new javax.swing.JLabel();
        quatriemeCarte = new javax.swing.JLabel();
        troisiemeCarte = new javax.swing.JLabel();
        secondeCarte = new javax.swing.JLabel();
        premiereCarte = new javax.swing.JLabel();
        jcbPrem = new javax.swing.JComboBox();
        jcbSec = new javax.swing.JComboBox();
        jcbTroi = new javax.swing.JComboBox();
        jcbQuatre = new javax.swing.JComboBox();
        jcbCinq = new javax.swing.JComboBox();
        jcbSix = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Dans quel ordre voulez vous mettre les 6 prochaines cartes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        jPanel1.add(jLabel1, gridBagConstraints);

        sixiemeCarte.setBackground(new java.awt.Color(51, 0, 51));
        sixiemeCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        sixiemeCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        sixiemeCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel1.add(sixiemeCarte, gridBagConstraints);

        cinquiemeCarte.setBackground(new java.awt.Color(0, 102, 102));
        cinquiemeCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        cinquiemeCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        cinquiemeCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(cinquiemeCarte, gridBagConstraints);

        quatriemeCarte.setBackground(new java.awt.Color(102, 204, 0));
        quatriemeCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        quatriemeCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        quatriemeCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(quatriemeCarte, gridBagConstraints);

        troisiemeCarte.setBackground(new java.awt.Color(204, 0, 153));
        troisiemeCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        troisiemeCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        troisiemeCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(troisiemeCarte, gridBagConstraints);

        secondeCarte.setBackground(new java.awt.Color(51, 255, 255));
        secondeCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        secondeCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        secondeCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(secondeCarte, gridBagConstraints);

        premiereCarte.setBackground(new java.awt.Color(255, 102, 102));
        premiereCarte.setMaximumSize(new java.awt.Dimension(150, 215));
        premiereCarte.setMinimumSize(new java.awt.Dimension(150, 215));
        premiereCarte.setPreferredSize(new java.awt.Dimension(150, 215));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(premiereCarte, gridBagConstraints);

        jcbPrem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbPrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPremActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbPrem, gridBagConstraints);

        jcbSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbSec.setEnabled(false);
        jcbSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSecActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbSec, gridBagConstraints);

        jcbTroi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbTroi.setEnabled(false);
        jcbTroi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTroiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbTroi, gridBagConstraints);

        jcbQuatre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbQuatre.setEnabled(false);
        jcbQuatre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbQuatreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbQuatre, gridBagConstraints);

        jcbCinq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbCinq.setEnabled(false);
        jcbCinq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCinqActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbCinq, gridBagConstraints);

        jcbSix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Position :", "1", "2", "3", "4", "5", "6" }));
        jcbSix.setEnabled(false);
        jcbSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jcbSix, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Valider");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCinqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCinqActionPerformed
        // TODO add your handling code here:
        switch (jcbCinq.getSelectedIndex()) {
            case 0:
                for (int i = 4; i < 6; i++) {
                    ordre[i] = 0;
                }
                jcbSix.setEnabled(false);

                break;
            default:
                if (ordre[4] == 0) {
                    ordre[4] = Integer.parseInt((String) jcbCinq.getSelectedItem());
                    jcbSix.removeItem(String.valueOf(ordre[4]));
                } else {
                    jcbSix.addItem(String.valueOf(ordre[4]));
                    ordre[5] = Integer.parseInt((String) jcbCinq.getSelectedItem());
                    jcbSix.removeItem(String.valueOf(ordre[4]));
                }
                jcbSix.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_jcbCinqActionPerformed

        private void jcbPremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPremActionPerformed
            // TODO add your handling code here:
            switch (jcbPrem.getSelectedIndex()) {
                case 0:
                    for (int i = 0; i < 6; i++) {
                        ordre[i] = 0;
                    }
                    jcbSec.setEnabled(false);
                    jcbTroi.setEnabled(false);
                    jcbQuatre.setEnabled(false);
                    jcbCinq.setEnabled(false);
                    jcbSix.setEnabled(false);

                    break;
                default:
                    if (ordre[0] == 0) {
                        ordre[0] = Integer.parseInt((String) jcbPrem.getSelectedItem());
                        jcbSec.removeItem(String.valueOf(ordre[0]));
                        jcbTroi.removeItem(String.valueOf(ordre[0]));
                        jcbQuatre.removeItem(String.valueOf(ordre[0]));
                        jcbCinq.removeItem(String.valueOf(ordre[0]));
                        jcbSix.removeItem((String) jcbPrem.getSelectedItem());
                    } else {
                        jcbSec.addItem(String.valueOf(ordre[0]));
                        jcbTroi.addItem(String.valueOf(ordre[0]));
                        jcbQuatre.addItem(String.valueOf(ordre[0]));
                        jcbCinq.addItem(String.valueOf(ordre[0]));
                        jcbSix.addItem(String.valueOf(ordre[0]));
                        ordre[0] = Integer.parseInt((String) jcbPrem.getSelectedItem());
                        jcbSec.removeItem(String.valueOf(ordre[0]));
                        jcbTroi.removeItem(String.valueOf(ordre[0]));
                        jcbQuatre.removeItem(String.valueOf(ordre[0]));
                        jcbCinq.removeItem(String.valueOf(ordre[0]));
                        jcbSix.removeItem(String.valueOf(ordre[0]));
                    }
                    jcbSec.setEnabled(true);
                    break;
            }
    }//GEN-LAST:event_jcbPremActionPerformed

    private void jcbSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSecActionPerformed
        // TODO add your handling code here:
        switch (jcbSec.getSelectedIndex()) {
            case 0:
                for (int i = 1; i < 6; i++) {
                    ordre[i] = 0;
                }
                jcbTroi.setEnabled(false);
                jcbQuatre.setEnabled(false);
                jcbCinq.setEnabled(false);
                jcbSix.setEnabled(false);

                break;
            default:
                if (ordre[1] == 0) {
                    ordre[1] = Integer.parseInt((String) jcbSec.getSelectedItem());
                    jcbTroi.removeItem(String.valueOf(ordre[1]));
                    jcbQuatre.removeItem(String.valueOf(ordre[1]));
                    jcbCinq.removeItem(String.valueOf(ordre[1]));
                    jcbSix.removeItem(String.valueOf(ordre[1]));
                } else {

                    jcbTroi.addItem(String.valueOf(ordre[1]));
                    jcbQuatre.addItem(String.valueOf(ordre[1]));
                    jcbCinq.addItem(String.valueOf(ordre[1]));
                    jcbSix.addItem(String.valueOf(ordre[1]));
                    ordre[1] = Integer.parseInt((String) jcbSec.getSelectedItem());
                    jcbTroi.removeItem(String.valueOf(ordre[1]));
                    jcbQuatre.removeItem(String.valueOf(ordre[1]));
                    jcbCinq.removeItem(String.valueOf(ordre[1]));
                    jcbSix.removeItem(String.valueOf(ordre[1]));
                }
                jcbTroi.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_jcbSecActionPerformed

    private void jcbTroiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTroiActionPerformed
        // TODO add your handling code here:
        switch (jcbTroi.getSelectedIndex()) {
            case 0:
                for (int i = 2; i < 6; i++) {
                    ordre[i] = 0;
                }
                jcbQuatre.setEnabled(false);
                jcbCinq.setEnabled(false);
                jcbSix.setEnabled(false);

                break;
            default:
                if (ordre[2] == 0) {
                    ordre[2] = Integer.parseInt((String) jcbTroi.getSelectedItem());
                    jcbQuatre.removeItem(String.valueOf(ordre[2]));
                    jcbCinq.removeItem(String.valueOf(ordre[2]));
                    jcbSix.removeItem(String.valueOf(ordre[2]));
                } else {
                    jcbQuatre.addItem(String.valueOf(ordre[2]));
                    jcbCinq.addItem(String.valueOf(ordre[2]));
                    jcbSix.addItem(String.valueOf(ordre[2]));
                    ordre[2] = Integer.parseInt((String) jcbTroi.getSelectedItem());
                    jcbQuatre.removeItem(String.valueOf(ordre[2]));
                    jcbCinq.removeItem(String.valueOf(ordre[2]));
                    jcbSix.removeItem(String.valueOf(ordre[2]));
                }
                jcbQuatre.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jcbTroiActionPerformed

    private void jcbQuatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuatreActionPerformed
        // TODO add your handling code here:
        switch (jcbQuatre.getSelectedIndex()) {
            case 0:
                for (int i = 3; i < 6; i++) {
                    ordre[i] = 0;
                }
                jcbCinq.setEnabled(false);
                jcbSix.setEnabled(false);

                break;
            default:
                if (ordre[3] == 0) {
                    ordre[3] = Integer.parseInt((String) jcbQuatre.getSelectedItem());
                    jcbCinq.removeItem(String.valueOf(ordre[3]));
                    jcbSix.removeItem(String.valueOf(ordre[3]));
                } else {
                    jcbCinq.addItem(String.valueOf(ordre[3]));
                    jcbSix.addItem(String.valueOf(ordre[3]));
                    ordre[3] = Integer.parseInt((String) jcbQuatre.getSelectedItem());
                    jcbCinq.removeItem(String.valueOf(ordre[3]));
                    jcbSix.removeItem(String.valueOf(ordre[3]));
                }
                jcbCinq.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jcbQuatreActionPerformed

    private void jcbSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSixActionPerformed
        // TODO add your handling code here:
        switch (jcbSix.getSelectedIndex()) {
            case 0:
                jButton1.setEnabled(false);

                break;
            default:

                ordre[5] = Integer.parseInt((String) jcbSix.getSelectedItem());

                jButton1.setEnabled(true);
                break;
        }


    }//GEN-LAST:event_jcbSixActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String[] temp = new String[6];
        for (int i = 0; i < 6; i++) {
            temp[i] = pileCarteEnnemis.get(i);
        }
        for (int i = 0; i < 6; i++) {
            pileCarteEnnemis.remove(0);
        }
        String[] temp2 = new String[6];
        for (int i = 0; i < 6; i++) {
            temp2[ordre[i]-1]=temp[i];
        }
        this.dispose();
        ArrayList<String> temp3=new ArrayList<>();
        for(String s:temp2)
        {
            temp3.add(s);
        }
        pileCarteEnnemis.addAll(0, temp3);

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoixOrdreCarteEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoixOrdreCarteEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoixOrdreCarteEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoixOrdreCarteEnnemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChoixOrdreCarteEnnemi dialog = new ChoixOrdreCarteEnnemi(new javax.swing.JFrame(), true, pileCarteEnnemis);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinquiemeCarte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbCinq;
    private javax.swing.JComboBox jcbPrem;
    private javax.swing.JComboBox jcbQuatre;
    private javax.swing.JComboBox jcbSec;
    private javax.swing.JComboBox jcbSix;
    private javax.swing.JComboBox jcbTroi;
    private javax.swing.JLabel premiereCarte;
    private javax.swing.JLabel quatriemeCarte;
    private javax.swing.JLabel secondeCarte;
    private javax.swing.JLabel sixiemeCarte;
    private javax.swing.JLabel troisiemeCarte;
    // End of variables declaration//GEN-END:variables
}
