/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yggdrasil.vue;

import javax.swing.JFrame;
import yggdrasil.Dieu.*;
import yggdrasil.Partie;

/**
 *
 * @author Mathias
 */
public class choixJoueur extends javax.swing.JPanel {

    private boolean name;
    /**
     * Creates new form choixJoueur
     */
    private JFrame page;
    private Partie partie;
    private String[] joueur;

    public choixJoueur(JFrame page, Partie p) {
        this.page = page;
        this.partie = p;
        joueur = new String[6];
        for (int i = 0; i < 6; i++) {
            joueur[i] = "";
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JcomboJoueur1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        imageJoueur1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JcomboJoueur2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        imageJoueur2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        JcomboJoueur3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        imageJoueur3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        JcomboJoueur4 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        imageJoueur4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        JcomboJoueur5 = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        imageJoueur5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        JcomboJoueur6 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        imageJoueur6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Avec quels dieux voulez vous jouer?");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(6, 3));

        jLabel2.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Joueur 1 : ");
        jLabel2.setToolTipText("");
        jLabel2.setMaximumSize(new java.awt.Dimension(30, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(30, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel1.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("Jlabel2");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 200};
        jPanel3.setLayout(jPanel3Layout);

        JcomboJoueur1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(JcomboJoueur1, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(imageJoueur1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jLabel3.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Joueur 2 :");
        jPanel1.add(jLabel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 200};
        jPanel4.setLayout(jPanel4Layout);

        JcomboJoueur2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur2.setEnabled(false);
        JcomboJoueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(JcomboJoueur2, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(imageJoueur2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jLabel4.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Joueur 3 :");
        jPanel1.add(jLabel4);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
        jPanel7Layout.columnWidths = new int[] {0, 200};
        jPanel7.setLayout(jPanel7Layout);

        JcomboJoueur3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur3.setEnabled(false);
        JcomboJoueur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel7.add(JcomboJoueur3, gridBagConstraints);

        jPanel1.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(imageJoueur3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jLabel5.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Joueur 4 :");
        jPanel1.add(jLabel5);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel9Layout = new java.awt.GridBagLayout();
        jPanel9Layout.columnWidths = new int[] {0, 200};
        jPanel9.setLayout(jPanel9Layout);

        JcomboJoueur4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur4.setEnabled(false);
        JcomboJoueur4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel9.add(JcomboJoueur4, gridBagConstraints);

        jPanel1.add(jPanel9);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(imageJoueur4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jLabel6.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Joueur 5 : ");
        jPanel1.add(jLabel6);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel10Layout = new java.awt.GridBagLayout();
        jPanel10Layout.columnWidths = new int[] {0, 200};
        jPanel10.setLayout(jPanel10Layout);

        JcomboJoueur5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur5.setEnabled(false);
        JcomboJoueur5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur5ActionPerformed(evt);
            }
        });
        jPanel10.add(JcomboJoueur5, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(imageJoueur5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel11);

        jLabel7.setFont(new java.awt.Font("Yggdrasil", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Joueur 6 :");
        jPanel1.add(jLabel7);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        java.awt.GridBagLayout jPanel12Layout = new java.awt.GridBagLayout();
        jPanel12Layout.columnWidths = new int[] {0, 200};
        jPanel12.setLayout(jPanel12Layout);

        JcomboJoueur6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix dieu : ", "Odin", "Thor", "Frey", "Heimdall", "Tyr", "Freyja" }));
        JcomboJoueur6.setEnabled(false);
        JcomboJoueur6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboJoueur6ActionPerformed(evt);
            }
        });
        jPanel12.add(JcomboJoueur6, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel13.add(imageJoueur6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Yggdrasil", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Continuer");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel14.add(jButton1);

        add(jPanel14, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void JcomboJoueur6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur6ActionPerformed
        // TODO add your handling code here:
        switch (JcomboJoueur6.getSelectedIndex()) {
            case 0:
                joueur[5] = "";
                imageJoueur6.setIcon(null);
                break;
            default:
                joueur[5] = (String) JcomboJoueur6.getSelectedItem();
                imageJoueur6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[5] + ".jpg")));
                break;
        }
    }//GEN-LAST:event_JcomboJoueur6ActionPerformed

    private void JcomboJoueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur1ActionPerformed

        // TODO add your handling code here:

        switch (JcomboJoueur1.getSelectedIndex()) {
            case 0:
                for (int i = 0; i < 6; i++) {
                    joueur[i] = "";
                }
                JcomboJoueur2.setEnabled(false);
                JcomboJoueur3.setEnabled(false);
                JcomboJoueur4.setEnabled(false);
                JcomboJoueur5.setEnabled(false);
                JcomboJoueur6.setEnabled(false);
                imageJoueur2.setIcon(null);
                imageJoueur3.setIcon(null);
                imageJoueur4.setIcon(null);
                imageJoueur5.setIcon(null);
                imageJoueur6.setIcon(null);
                imageJoueur1.setIcon(null);
                jButton1.setEnabled(false);
                break;
            default:
                jButton1.setEnabled(true);
                if (joueur[0].isEmpty()) {
                    joueur[0] = (String) JcomboJoueur1.getSelectedItem();
                    imageJoueur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[0] + ".jpg")));
                    JcomboJoueur2.removeItem(joueur[0]);
                    JcomboJoueur3.removeItem(joueur[0]);
                    JcomboJoueur4.removeItem(joueur[0]);
                    JcomboJoueur5.removeItem(joueur[0]);
                    JcomboJoueur6.removeItem(joueur[0]);
                } else {
                    JcomboJoueur2.addItem(joueur[0]);
                    JcomboJoueur3.addItem(joueur[0]);
                    JcomboJoueur4.addItem(joueur[0]);
                    JcomboJoueur5.addItem(joueur[0]);
                    JcomboJoueur6.addItem(joueur[0]);
                    joueur[0] = (String) JcomboJoueur1.getSelectedItem();
                    imageJoueur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[0] + ".jpg")));
                    JcomboJoueur2.removeItem(joueur[0]);
                    JcomboJoueur3.removeItem(joueur[0]);
                    JcomboJoueur4.removeItem(joueur[0]);
                    JcomboJoueur5.removeItem(joueur[0]);
                    JcomboJoueur6.removeItem(joueur[0]);
                }
                JcomboJoueur2.setEnabled(true);
                break;
        }


    }//GEN-LAST:event_JcomboJoueur1ActionPerformed

    private void JcomboJoueur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur3ActionPerformed
        // TODO add your handling code here:
        switch (JcomboJoueur3.getSelectedIndex()) {
            case 0:
                for (int i = 2; i < 6; i++) {
                    joueur[i] = "";
                }
                JcomboJoueur4.setEnabled(false);
                JcomboJoueur5.setEnabled(false);
                JcomboJoueur6.setEnabled(false);
                imageJoueur4.setIcon(null);
                imageJoueur5.setIcon(null);
                imageJoueur6.setIcon(null);
                imageJoueur3.setIcon(null);
                break;
            default:
                if (joueur[2].isEmpty()) {
                    joueur[2] = (String) JcomboJoueur3.getSelectedItem();
                    imageJoueur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[2] + ".jpg")));
                    JcomboJoueur4.removeItem(joueur[2]);
                    JcomboJoueur5.removeItem(joueur[2]);
                    JcomboJoueur6.removeItem(joueur[2]);
                } else {
                    JcomboJoueur4.addItem(joueur[2]);
                    JcomboJoueur5.addItem(joueur[2]);
                    JcomboJoueur6.addItem(joueur[2]);
                    joueur[2] = (String) JcomboJoueur3.getSelectedItem();
                    imageJoueur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[2] + ".jpg")));
                    JcomboJoueur4.removeItem(joueur[2]);
                    JcomboJoueur5.removeItem(joueur[2]);
                    JcomboJoueur6.removeItem(joueur[2]);
                }
                JcomboJoueur4.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_JcomboJoueur3ActionPerformed

    private void JcomboJoueur4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur4ActionPerformed
        // TODO add your handling code here:
        switch (JcomboJoueur4.getSelectedIndex()) {
            case 0:
                for (int i = 3; i < 6; i++) {
                    joueur[i] = "";
                }
                JcomboJoueur5.setEnabled(false);
                JcomboJoueur6.setEnabled(false);
                imageJoueur5.setIcon(null);
                imageJoueur6.setIcon(null);
                imageJoueur4.setIcon(null);
                break;
            default:
                if (joueur[3].isEmpty()) {
                    joueur[3] = (String) JcomboJoueur4.getSelectedItem();
                    imageJoueur4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[3] + ".jpg")));
                    JcomboJoueur5.removeItem(joueur[3]);
                    JcomboJoueur6.removeItem(joueur[3]);
                } else {
                    JcomboJoueur5.addItem(joueur[3]);
                    JcomboJoueur6.addItem(joueur[3]);
                    joueur[3] = (String) JcomboJoueur4.getSelectedItem();
                    imageJoueur4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[3] + ".jpg")));
                    JcomboJoueur5.removeItem(joueur[3]);
                    JcomboJoueur6.removeItem(joueur[3]);
                }
                JcomboJoueur5.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_JcomboJoueur4ActionPerformed

    private void JcomboJoueur5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur5ActionPerformed
        // TODO add your handling code here:
        switch (JcomboJoueur5.getSelectedIndex()) {
            case 0:
                for (int i = 4; i < 6; i++) {
                    joueur[i] = "";
                }
                JcomboJoueur6.setEnabled(false);
                imageJoueur6.setIcon(null);
                imageJoueur5.setIcon(null);
                break;
            default:
                if (joueur[4].isEmpty()) {
                    joueur[4] = (String) JcomboJoueur5.getSelectedItem();
                    imageJoueur5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[4] + ".jpg")));
                    JcomboJoueur5.removeItem(joueur[4]);
                    JcomboJoueur6.removeItem(joueur[4]);
                } else {
                    JcomboJoueur5.addItem(joueur[4]);
                    JcomboJoueur6.addItem(joueur[4]);
                    joueur[4] = (String) JcomboJoueur5.getSelectedItem();
                    imageJoueur5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[4] + ".jpg")));
                    JcomboJoueur6.removeItem(joueur[4]);
                }
                JcomboJoueur6.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_JcomboJoueur5ActionPerformed

    private void JcomboJoueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboJoueur2ActionPerformed
        // TODO add your handling code here:
        switch (JcomboJoueur2.getSelectedIndex()) {
            case 0:
                for (int i = 1; i < 6; i++) {
                    joueur[i] = "";
                }
                JcomboJoueur3.setEnabled(false);
                JcomboJoueur4.setEnabled(false);
                JcomboJoueur5.setEnabled(false);
                JcomboJoueur6.setEnabled(false);
                imageJoueur3.setIcon(null);
                imageJoueur4.setIcon(null);
                imageJoueur5.setIcon(null);
                imageJoueur6.setIcon(null);
                imageJoueur2.setIcon(null);
                break;
            default:
                if (joueur[1].isEmpty()) {
                    joueur[1] = (String) JcomboJoueur2.getSelectedItem();
                    imageJoueur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[1] + ".jpg")));
                    JcomboJoueur3.removeItem(joueur[1]);
                    JcomboJoueur4.removeItem(joueur[1]);
                    JcomboJoueur5.removeItem(joueur[1]);
                    JcomboJoueur6.removeItem(joueur[1]);
                } else {
                    JcomboJoueur3.addItem(joueur[1]);
                    JcomboJoueur4.addItem(joueur[1]);
                    JcomboJoueur5.addItem(joueur[1]);
                    JcomboJoueur6.addItem(joueur[1]);
                    joueur[1] = (String) JcomboJoueur2.getSelectedItem();
                    imageJoueur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + joueur[1] + ".jpg")));
                    JcomboJoueur3.removeItem(joueur[1]);
                    JcomboJoueur4.removeItem(joueur[1]);
                    JcomboJoueur5.removeItem(joueur[1]);
                    JcomboJoueur6.removeItem(joueur[1]);
                }
                JcomboJoueur3.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_JcomboJoueur2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        for (int i = 0; i < 6; i++) {
            if (!joueur[i].isEmpty()) {
                if (joueur[i].compareTo("Odin") == 0) {
                    partie.ajouterDieu(new Odin());
                } else if (joueur[i].compareTo("Frey") == 0) {
                    partie.ajouterDieu(new Frey());
                } else if (joueur[i].compareTo("Freyja") == 0) {
                    partie.ajouterDieu(new Freyja());
                } else if (joueur[i].compareTo("Heimdall") == 0) {
                    partie.ajouterDieu(new Heimdall());
                } else if (joueur[i].compareTo("Thor") == 0) {
                    partie.ajouterDieu(new Thor());
                } else if (joueur[i].compareTo("Tyr") == 0) {
                    partie.ajouterDieu(new Tyr());
                }
            }
        }
        partie.setDieuActuel((Dieu)partie.getlDieu().get(0));
        page.getContentPane().removeAll();
        page.getContentPane().add(new EcranPrincipal(page, partie));
        page.revalidate();
        if ("Odin".equals(partie.getDieuActuel().getNom())&&Dieu.pouvoirDieu) {
            String e = (String)partie.getPileCarteEnnemis().get(0);
            String e1 =(String) partie.getPileCarteEnnemis().get(1);
            OdinTire dt = new OdinTire(page, true, e,e1);
            dt.setLocationRelativeTo(page);
            dt.setVisible(true);
            int choix=dt.getChoix();
            String ec=(String)partie.getPileCarteEnnemis().get(choix);
            partie.getPileCarteEnnemis().remove(ec);
            partie.appliquerEnnemi(page, ec);

        } else {
            String e = (String)partie.getPileCarteEnnemis().get(0);
            DieuTire dt = new DieuTire(page, true, e);
            dt.setLocationRelativeTo(page);
            dt.setVisible(true);
            partie.getPileCarteEnnemis().remove(0);
            partie.appliquerEnnemi(page, e);
        }

        page.getContentPane().removeAll();
        page.getContentPane().add(new EcranPrincipal(page, partie));
        page.revalidate();
    }//GEN-LAST:event_jButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JcomboJoueur1;
    private javax.swing.JComboBox JcomboJoueur2;
    private javax.swing.JComboBox JcomboJoueur3;
    private javax.swing.JComboBox JcomboJoueur4;
    private javax.swing.JComboBox JcomboJoueur5;
    private javax.swing.JComboBox JcomboJoueur6;
    private javax.swing.JLabel imageJoueur1;
    private javax.swing.JLabel imageJoueur2;
    private javax.swing.JLabel imageJoueur3;
    private javax.swing.JLabel imageJoueur4;
    private javax.swing.JLabel imageJoueur5;
    private javax.swing.JLabel imageJoueur6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
